package UPP.NaucnaCentrala.model;

public enum ArticleStatus {
	SUBMITTED_FOR_EDITOR,
	NEEDS_FORMATTING,
	FOR_PICKING_FIELD_EDITOR,
	FOR_PICKING_REVIWERS,
	FOR_FIRST_REVIEW,
	FOR_SECOND_REVIEW,
	REVIEWED_FOR_EDITOR_FIRST,
	NEEDS_CORRECTION,
	CORRECTED_FOR_EDITOR,
	APPROVED,
	DISAPPROVED
}
